# Generated by Django 5.1.1 on 2024-09-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_patientdetail_medicalrecord_bloodgroup_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientdetail',
            options={'ordering': ['updated', 'created']},
        ),
        migrations.RemoveField(
            model_name='appoinment',
            name='purpose',
        ),
        migrations.AddField(
            model_name='appoinment',
            name='appointment_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='appoinment',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appoinment',
            name='medical_department',
            field=models.CharField(blank=True, choices=[('Anesthetics', 'Anesthetics'), ('Cardiology', 'Cardiology'), ('Dermatology', 'Dermatology'), ('Ear, nose and throat (ENT)', 'Ear, nose and throat (ENT)'), ('Elderly services department', 'Elderly services department'), ('Gastroenterology', 'Gastroenterology'), ('General Surgery', 'General Surgery'), ('Hematology', 'Hematology'), ('Neurology', 'Neurology'), ('Nutrition and dietetics', 'Nutrition and dietetics'), ('Gynecology', 'Cardiology'), ('Oncology', 'Oncology'), ('Ophthalmology', 'Ophthalmology'), ('Orthopedics', 'Orthopedics'), ('Pediatrics', 'Pediatrics'), ('Physiotherapy', 'Physiotherapy')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appoinment',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='height',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='medical_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='weight',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='patientdetail',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
    ]
