# Generated by Django 5.1.1 on 2024-09-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_alter_patientdetail_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='bloodgroup',
            field=models.CharField(blank=True, choices=[('A +ve', 'A +ve'), ('A -ve', 'A -ve'), ('B +ve', 'B +ve'), ('B -ve', 'B -ve'), ('AB +ve', 'AB +ve'), ('AB -ve', 'AB -ve'), ('O +ve', 'O +ve'), ('O -ve', 'O -ve')], max_length=100, null=True),
        ),
    ]
